### ISSUE TITLE
Kompatibel zu CTO Version 4.13.18 und PHP 8.2

### ISSUE THREAD

**Issue by dp-designpilot** [leycommediasolutions/contao_elementsets#8]
Gute Tag
Könnt Ihr die Elementsets Erweiterung auch für 4.13.18 und PHP 8.2 freigeben ??? Weil die Erweiterung macht es einfach so viel einfacher.

Freundliche Grüsse
designpilot

**Comment by leycommediasolutions** [comment]
Die Erweiterung steht nun für 4.13 und PHP 8 bereit.
